//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public abstract class IsoGUI
{
	public IsoGUI (){

	}

	public bool captureEvent(ControllerEventArgs args){
		return true;
	}

	public abstract void draw ();

}


